<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_London, UK</name>
   <tag></tag>
   <elementGuidId>2ec950e6-701a-4079-90f3-8dce2cc5d2b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3ffab677-9f41-4152-bf77-faf7f3060b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer select-none relative py-3 pl-4 pr-4 text-white bg-primary-100</value>
      <webElementGuid>7fc6071b-ce2f-412b-bd2b-aed51f3cf797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-16</value>
      <webElementGuid>50da7cdb-29e1-4c6b-a7c3-1ccf060a3e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>72cc9a23-81d3-43eb-8959-4ffc7cea66f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2adc9ceb-eae5-42db-97c4-b63214be5f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68d5970e-9bf6-49ed-be81-fa8b2fb3ada5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>8f730553-3711-4cf1-9d22-87b9ee9d6c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>London, UK</value>
      <webElementGuid>61ad0326-caf9-4420-a248-0f8a7b4c0745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-16&quot;)</value>
      <webElementGuid>406828ee-a744-436a-9d06-61369a88b892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-16']</value>
      <webElementGuid>251a50ee-262c-48a5-926b-dbe85c7e61f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-13']/div/li</value>
      <webElementGuid>a92f1636-4395-4a8f-8351-51778c4a0549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::li[1]</value>
      <webElementGuid>c74b6577-94b8-45d6-8bd3-9a8610bb265e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML &amp; KYC Policy'])[1]/following::li[2]</value>
      <webElementGuid>7cb8fb18-45fa-4d2e-b760-ba0d7e69cd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'headlessui-combobox-option-16', '&quot;', ')')])[1]/preceding::li[10]</value>
      <webElementGuid>91dc9367-71ac-46a1-934f-68b2f797abe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>ef999a9d-da42-4968-a7ca-88d45d34e287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-16' and (text() = 'London, UK' or . = 'London, UK')]</value>
      <webElementGuid>acdc6b5d-b4c3-4019-94d9-a7c307849c81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
