<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SELECT ROOM</name>
   <tag></tag>
   <elementGuidId>9927731d-a96e-4b80-8847-20aa1e66c8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>279f8066-73a5-481f-95a5-ebcf72f9da51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71809c92-1a7f-45af-8bdb-4372a848ce1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-white bg-blue-500 hover:bg-indigo-700 focus:ring-indigo-500 border border-transparent shadow-sm focus:outline-none  w-full py-2 px-2</value>
      <webElementGuid>3543998f-de09-46ed-803a-3dc48d15dac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECT ROOM</value>
      <webElementGuid>c9433115-3b05-4dc9-842e-abbbf32aec8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-disclosure-panel-16&quot;)/div[@class=&quot;flex flex-col gap-2 md:gap-6 w-full md:w-8/12&quot;]/div[@class=&quot;flex flex-col md:flex-row w-full border rounded-md h-full&quot;]/div[@class=&quot;w-full md:w-3/12 p-2 md:px-6 md:py-4 flex flex-col gap-3 justify-evenly items-end&quot;]/button[@class=&quot;inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-white bg-blue-500 hover:bg-indigo-700 focus:ring-indigo-500 border border-transparent shadow-sm focus:outline-none  w-full py-2 px-2&quot;]</value>
      <webElementGuid>d8fd84a1-bc8e-49c4-8af2-73a15d8b1604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>0e1570be-d666-49cf-a18a-8eacd7a65fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-disclosure-panel-16']/div[2]/div/div[3]/button</value>
      <webElementGuid>310fdfd4-6185-4b01-b2a9-d2d2a591ec2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wellness Area'])[2]/following::button[5]</value>
      <webElementGuid>285729fa-9350-4d9a-813b-4e3fd4a4c72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cleanliness'])[2]/following::button[5]</value>
      <webElementGuid>84ec70bd-43fb-4c87-ba99-a5c7ba6bd463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay at hotel'])[1]/preceding::button[165]</value>
      <webElementGuid>63a390cd-2fd6-41f7-a594-f0d1020c7247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay at hotel'])[2]/preceding::button[167]</value>
      <webElementGuid>aa662627-e77c-454c-81bd-f9dfd0aec4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]/button</value>
      <webElementGuid>b50cb40e-cf17-40d1-aeb8-6123b899de80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'SELECT ROOM' or . = 'SELECT ROOM')]</value>
      <webElementGuid>d0a6fc16-04d4-467e-afe0-a06de410dc85</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
