<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Allow essential and optional cookies</name>
   <tag></tag>
   <elementGuidId>b96a1b7a-8d91-42d2-b376-f0d2ce9d8b9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='u_0_b_/U']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dea7ebc4-b01c-46e8-9cca-6a6b352cb793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c7ca69c-4b13-43e7-bb85-147273d3ba4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9xo7 _4jy3 _4jy1 selected _51sy</value>
      <webElementGuid>f36c195c-b7a7-4aad-b433-05e60b2f8e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cookiebanner</name>
      <type>Main</type>
      <value>accept_button</value>
      <webElementGuid>0bb629d2-993c-400f-87f8-c912c0577a76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cookie-policy-manage-dialog-accept-button</value>
      <webElementGuid>e0b09345-bc35-43fc-ba44-fb72ff4a8cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Allow essential and optional cookies</value>
      <webElementGuid>17901792-9678-4010-a5a3-17adfff1e381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0a361312-f3a6-4737-ad92-c5a06790561c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_b_/U</value>
      <webElementGuid>8308307b-3527-48aa-94a6-864c7b7cd9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Allow essential and optional cookies</value>
      <webElementGuid>662f852f-478d-4bcb-a41e-659b7eb59723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_b_/U&quot;)</value>
      <webElementGuid>d9c18a86-8199-407a-9a86-f2fd0954f714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='u_0_b_/U']</value>
      <webElementGuid>eb1408be-5352-41a2-8451-94eccb334f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='facebook']/body/div[3]/div[2]/div/div/div/div/div[3]/button[2]</value>
      <webElementGuid>feb2e6dc-9452-4cbb-b395-118933fd8b64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Only allow essential cookies'])[1]/following::button[1]</value>
      <webElementGuid>7e7f749a-329b-4e7a-8fc1-5ae8ae344b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opera'])[1]/following::button[2]</value>
      <webElementGuid>8786fd1f-9f2d-42ad-bd74-c5c998c0b4aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'u_0_b_/U', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>dd80267f-ae91-4db6-846c-3076b8dbccb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Allow essential and optional cookies']/parent::*</value>
      <webElementGuid>66d13f58-c41e-457c-9794-ea2ce40bac26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>af58f827-121e-418b-b9f7-7919f114ba7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Allow essential and optional cookies' and @type = 'submit' and @id = 'u_0_b_/U' and (text() = 'Allow essential and optional cookies' or . = 'Allow essential and optional cookies')]</value>
      <webElementGuid>36977b35-acc9-4f46-92ed-349632131959</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
