<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__cursor-pointer</name>
   <tag></tag>
   <elementGuidId>bee8d9a1-b8d3-4559-a1f4-cc15fc3a9318</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>abea20cc-57e5-4c7d-acde-1533981a602b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/logo.svg 1x, /images/logo.svg 2x</value>
      <webElementGuid>b65c79a2-b9d6-4332-b07a-b7f7e88e9c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo.svg</value>
      <webElementGuid>a2bd97d8-d63b-4326-bc12-e24b2aeec6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a5376777-20dd-4aa5-b553-8471ecb26701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>41a59e8a-e00d-4202-b62b-7a7d9271a9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>671bfa78-58d5-4a2b-a7e9-e907aaf24c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;w-full z-50 relative&quot;]/div[@class=&quot;relative bg-white shadow-md w-full z-[50]&quot;]/div[1]/div[@class=&quot;flex items-center justify-between bg-white px-4 py-2&quot;]/span[1]/img[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>eca52a65-068c-458e-ba43-514644292ea8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/span/img</value>
      <webElementGuid>263f4d1e-186c-49e6-924e-92a879889016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>1167467e-4c41-4e96-bad2-5102659855a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/logo.svg']</value>
      <webElementGuid>60235340-a43d-4b76-9424-845f3fb57332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
