<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adult_rooms.0.adults.1.lastName_1_2</name>
   <tag></tag>
   <elementGuidId>cf675662-d309-4072-988b-6ccfff9b249d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rooms.0.adults.1.lastName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='rooms.0.adults.1.lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>419efb08-bd4f-4cf4-8a62-e8f3a6803133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a7821483-a627-46c7-a496-a33d9969c3e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>50577d4c-fb49-46c9-9b37-6fb9a471cb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5fcb6acf-31b7-402a-8ac6-fd1048a576be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full</value>
      <webElementGuid>8dfaa89a-8698-41b5-b4eb-125c6e9c88a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rooms.0.adults.1.lastName</value>
      <webElementGuid>aa65fee5-d426-4a06-807e-161bd771798a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg. Genesia</value>
      <webElementGuid>10388491-7bca-42e3-b35e-1a25c8af5c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bg_variant</name>
      <type>Main</type>
      <value>gray</value>
      <webElementGuid>16b42b70-5bb8-4265-ac59-2104fd5bc571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tr</value>
      <webElementGuid>bd75efba-b3ab-429d-8316-dc0c409f35ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;bg-gray-100&quot;]/div[@class=&quot;max-w-7xl mx-auto&quot;]/form[@class=&quot;w-full&quot;]/main[@class=&quot;grid grid-cols-6 md:grid-cols-12 gap-x-[32px] justify-center p-1 md:p-6&quot;]/div[@class=&quot;col-span-full md:col-span-7 flex flex-col gap-4&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-full&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;relative w-full flex flex-col p-4&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto mt-5 flex flex-col gap-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;p-3&quot;]/div[1]/div[@class=&quot;mt-5 w-full flex flex-col lg:flex-row justify-between gap-4&quot;]/div[@class=&quot;w-full flex items-start gap-4&quot;]/div[@class=&quot;w-full grid grid-cols-12 gap-1 md:gap-4&quot;]/div[@class=&quot;col-span-12 md:col-span-4&quot;]/div[@class=&quot;relative border border-gray-300 rounded-md shadow-sm hover:border-gray-700 bg-white px-3 py-2 focus-within:ring-1 focus-within:ring-primary-100 focus-within:border-primary-100 w-full&quot;]/input[@class=&quot;text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full&quot;]</value>
      <webElementGuid>0ae77612-e3fd-406f-9919-12a21715c660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rooms.0.adults.1.lastName']</value>
      <webElementGuid>31a9bcd7-a8c8-434d-9c18-f7874dd60375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/form/main/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div[5]/div/input</value>
      <webElementGuid>66eef2b4-0e6a-4996-b459-28ae7ad82cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div/input</value>
      <webElementGuid>9e0261a3-15a0-4845-887a-aadd724adf87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rooms.0.adults.1.lastName' and @placeholder = 'Eg. Genesia']</value>
      <webElementGuid>1756240f-7651-4bff-93f6-6e5672d7cb7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
