<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adult_rooms.0.adults.1.firstName</name>
   <tag></tag>
   <elementGuidId>a8aa0ebd-ccf2-46ae-8cd3-3208854622e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rooms.0.adults.1.firstName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='rooms.0.adults.1.firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>002addc3-c0a7-495b-84b3-c1e21051b7fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>41dc59ed-4b5c-441b-a482-7a0ffce298e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6908c36-c946-4a8d-b2ac-7e6c360b04d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>bd43109f-7dba-47e9-9ca1-659baed989a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full</value>
      <webElementGuid>56f407a9-770f-4515-b00b-05bee7931bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rooms.0.adults.1.firstName</value>
      <webElementGuid>6f56c46a-e15a-4dc2-a5c1-b006c5863ad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg. Philippe</value>
      <webElementGuid>2d11f94b-9b48-46d3-b044-09a1b913975b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bg_variant</name>
      <type>Main</type>
      <value>gray</value>
      <webElementGuid>b421648e-72fe-4bce-8e0f-095242cee11a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;bg-gray-100&quot;]/div[@class=&quot;max-w-7xl mx-auto&quot;]/form[@class=&quot;w-full&quot;]/main[@class=&quot;grid grid-cols-6 md:grid-cols-12 gap-x-[32px] justify-center p-1 md:p-6&quot;]/div[@class=&quot;col-span-full md:col-span-7 flex flex-col gap-4&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-full&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;relative w-full flex flex-col p-4&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto mt-5 flex flex-col gap-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;p-3&quot;]/div[1]/div[@class=&quot;mt-5 w-full flex flex-col lg:flex-row justify-between gap-4&quot;]/div[@class=&quot;w-full flex items-start gap-4&quot;]/div[@class=&quot;w-full grid grid-cols-12 gap-1 md:gap-4&quot;]/div[@class=&quot;col-span-8 md:col-span-5&quot;]/div[@class=&quot;relative border border-gray-300 rounded-md shadow-sm hover:border-gray-700 bg-white px-3 py-2 focus-within:ring-1 focus-within:ring-primary-100 focus-within:border-primary-100 w-full&quot;]/input[@class=&quot;text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full&quot;]</value>
      <webElementGuid>2a2d8bfd-5b6e-49bc-99c1-c5f9d90a2dc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rooms.0.adults.1.firstName']</value>
      <webElementGuid>f7c52132-0261-49d9-9fff-38193b563fe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/form/main/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>845d7ba1-4a62-41a9-a0c0-f8d841fcda7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>0778899b-1684-48f1-bc79-aa339e717653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rooms.0.adults.1.firstName' and @placeholder = 'Eg. Philippe']</value>
      <webElementGuid>8a9785d7-ff94-4b4c-a2f3-f0262eafa9f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
