<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adult_rooms.0.adults.1.lastName_1</name>
   <tag></tag>
   <elementGuidId>fdd82fe6-fc5b-428a-b5c2-c58d8828882e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rooms.0.adults.1.lastName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='rooms.0.adults.1.lastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>663d7f29-4e47-414c-a715-5033985e0d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2c9c6bb-8e97-4811-9f47-3303fddda186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b5f963b-8cc9-458e-9ac3-766d80f699e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>5ed856c8-f3b0-489f-89d2-9cc681b71daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full</value>
      <webElementGuid>a2f0bf29-c50e-4779-be46-2307b2a53b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rooms.0.adults.1.lastName</value>
      <webElementGuid>0094f1d6-569a-41a3-8818-d17efcdf19f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg. Kobi</value>
      <webElementGuid>27850315-e6ad-4266-85ab-e879ff895a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bg_variant</name>
      <type>Main</type>
      <value>gray</value>
      <webElementGuid>725ad16d-8006-4b23-b029-aa7f89649c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>T</value>
      <webElementGuid>20747496-3324-4268-83ea-aa2d0c664071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;bg-gray-100&quot;]/div[@class=&quot;max-w-7xl mx-auto&quot;]/form[@class=&quot;w-full&quot;]/main[@class=&quot;grid grid-cols-6 md:grid-cols-12 gap-x-[32px] justify-center p-1 md:p-6&quot;]/div[@class=&quot;col-span-full md:col-span-7 flex flex-col gap-4&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-full&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;relative w-full flex flex-col p-4&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto mt-5 flex flex-col gap-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;p-3&quot;]/div[1]/div[@class=&quot;mt-5 w-full flex flex-col lg:flex-row justify-between gap-4&quot;]/div[@class=&quot;w-full flex items-start gap-4&quot;]/div[@class=&quot;w-full grid grid-cols-12 gap-1 md:gap-4&quot;]/div[@class=&quot;col-span-12 md:col-span-4&quot;]/div[@class=&quot;relative border border-gray-300 rounded-md shadow-sm hover:border-gray-700 bg-white px-3 py-2 focus-within:ring-1 focus-within:ring-primary-100 focus-within:border-primary-100 w-full&quot;]/input[@class=&quot;text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full&quot;]</value>
      <webElementGuid>75a5baef-503b-42ce-bbd6-b65bf14122d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rooms.0.adults.1.lastName']</value>
      <webElementGuid>7796a690-75e7-4d8a-b350-61f200c199ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/form/main/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div[5]/div/input</value>
      <webElementGuid>20996615-3984-4d4f-99e0-2cfe99f2a5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[5]/div/input</value>
      <webElementGuid>2789b4fc-fbd3-411e-bdac-6559059fadb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rooms.0.adults.1.lastName' and @placeholder = 'Eg. Kobi']</value>
      <webElementGuid>df8929df-963c-4ab2-83b6-46b8ff99566e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
