<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Adult_rooms.0.adults.1.firstName_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>9fc9bbba-611b-4690-ab2c-9ac045117895</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;rooms.0.adults.1.firstName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='rooms.0.adults.1.firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4afc0b26-d42c-4bc1-80ee-f6a966368048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e847e54-5577-487b-9c6e-9d2159a45910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7e6b8f49-811f-4a4e-88ad-970858fa7ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>266ee8c6-a997-46dc-88f8-653d49415734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full</value>
      <webElementGuid>935281fe-b591-49ff-959b-ef4e7e9eb0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rooms.0.adults.1.firstName</value>
      <webElementGuid>4143b6f7-00e0-49b2-a0b3-19cb8fdc54af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg. Charleen</value>
      <webElementGuid>5a1cd003-1ce4-4f82-9257-05f713530502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bg_variant</name>
      <type>Main</type>
      <value>gray</value>
      <webElementGuid>ad992e23-d4b2-44e4-9478-4c17afd5020b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Lock</value>
      <webElementGuid>8694d65c-8f85-48b9-9f05-4fa7ecf5f258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;bg-gray-100&quot;]/div[@class=&quot;max-w-7xl mx-auto&quot;]/form[@class=&quot;w-full&quot;]/main[@class=&quot;grid grid-cols-6 md:grid-cols-12 gap-x-[32px] justify-center p-1 md:p-6&quot;]/div[@class=&quot;col-span-full md:col-span-7 flex flex-col gap-4&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-full&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;relative w-full flex flex-col p-4&quot;]/div[@class=&quot;flex flex-col gap-2&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto mt-5 flex flex-col gap-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;p-3&quot;]/div[1]/div[@class=&quot;mt-5 w-full flex flex-col lg:flex-row justify-between gap-4&quot;]/div[@class=&quot;w-full flex items-start gap-4&quot;]/div[@class=&quot;w-full grid grid-cols-12 gap-1 md:gap-4&quot;]/div[@class=&quot;col-span-8 md:col-span-5&quot;]/div[@class=&quot;relative border border-gray-300 rounded-md shadow-sm hover:border-gray-700 bg-white px-3 py-2 focus-within:ring-1 focus-within:ring-primary-100 focus-within:border-primary-100 w-full&quot;]/input[@class=&quot;text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full&quot;]</value>
      <webElementGuid>6bc62dfe-1ae0-47a7-9e88-a7461110e342</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='rooms.0.adults.1.firstName']</value>
      <webElementGuid>6f1fab48-15b0-4ee8-828f-2e09df0b71e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/form/main/div/div[2]/div/div/div[2]/div/div/div[2]/div/div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>81be889d-c8ac-4222-9acb-e47e760cb34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>e1a63f0c-46d0-4d15-945f-81971c1336f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'rooms.0.adults.1.firstName' and @placeholder = 'Eg. Charleen']</value>
      <webElementGuid>9a1559e4-fd4d-4e06-9d52-69fa9924901f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
