<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_headlessui-combobox-input-28</name>
   <tag></tag>
   <elementGuidId>c861f25b-d095-4776-b2e2-079063861412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-28']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-28</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f34a276d-a323-4fac-8a2c-09c8264c2522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!outline-none border-0 pl-0 outline-transparent  block w-full  truncate pt-5 pb-2 text-gray-900 placeholder-gray-900  sm:text-sm</value>
      <webElementGuid>27cbd413-efda-4f7f-95fb-f69bffdc83b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter destination or hotel name</value>
      <webElementGuid>a8f1a748-13fc-4902-b1cc-897816d8a1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>43c8fdfb-19fd-44ee-add5-adcfd037da45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-28</value>
      <webElementGuid>2b4346de-fd85-435b-bab2-2dce276249df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>3b5a9c08-4d0e-49d0-af41-c05431a2b419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>03006558-3f61-48c9-9ad4-fb97e16e0319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3c37a212-2101-473d-bbd6-e2befd980b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-28&quot;)</value>
      <webElementGuid>8dd585a6-3010-4401-bee6-1381c3ebe7a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-28']</value>
      <webElementGuid>fe3fb14f-a517-4d85-92b6-d121e8a28d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hotel']/div/div/div/form/div/div/div/div/div/div/input</value>
      <webElementGuid>167dfaa8-94d8-4b3b-829b-bf7f99cf914a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>bdd49a1a-6b71-4a41-a1fc-e759c90751ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter destination or hotel name' and @id = 'headlessui-combobox-input-28' and @type = 'text']</value>
      <webElementGuid>25eb6337-b685-4fe6-a459-a701450d7824</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
