<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ACCEPT</name>
   <tag></tag>
   <elementGuidId>caa1adbc-ac35-4f9a-bb15-94e510aa8ef4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee2538f3-a0c5-4135-946f-5af8b8f98cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0de4bf1d-d307-48a3-97e6-a08089b28d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-gray-600 bg-transparent hover:bg-gray-100 focus:ring-indigo-500 border border-gray-600 focus:outline-none  px-2 py-2 text-xs min-w-[110px] max-w-full border-white hover:bg-blue-400</value>
      <webElementGuid>be2b515b-8f05-4dc3-bf2d-1ec6582eb527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCEPT</value>
      <webElementGuid>5549e5dc-cf3c-44f0-b122-f77e01e660a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;w-full z-50 relative&quot;]/div[@class=&quot;fixed z-50  left-10 bottom-10&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto bg-blue-500 m-2 p-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;grid grid-cols-3&quot;]/div[@class=&quot;flex justify-end justify-items-center place-items-center&quot;]/button[@class=&quot;inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-gray-600 bg-transparent hover:bg-gray-100 focus:ring-indigo-500 border border-gray-600 focus:outline-none  px-2 py-2 text-xs min-w-[110px] max-w-full border-white hover:bg-blue-400&quot;]</value>
      <webElementGuid>38526415-804a-4954-a216-a4548666aa44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>d203ed12-f7d6-45b5-95c3-6f00cbb32098</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>1e4e33c8-1052-4d53-9c61-d2ec7c8c0a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[1]</value>
      <webElementGuid>dae82904-2f97-4e89-b9cb-e236be143cb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/preceding::button[1]</value>
      <webElementGuid>4892b009-6d38-469b-9d42-eaa94353b0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lock'])[1]/preceding::button[2]</value>
      <webElementGuid>803742c0-7268-432f-a36b-5d013f291935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>86a9aa14-c72a-4041-b990-fcba1416ff97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ACCEPT' or . = 'ACCEPT')]</value>
      <webElementGuid>1be2aed8-1c3b-4c28-ab10-4b9a3f56a10b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
