<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_headlessui-combobox-input-8</name>
   <tag></tag>
   <elementGuidId>c26c2fe3-3c76-4a30-abb9-3fdff012cf1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>500b3f89-c8d7-4f24-b1ae-77f883ceb950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ec9bbefb-400d-43ed-a8c3-aeb3a1ea51f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!outline-none border-0 pl-0 outline-transparent  block w-full  truncate pt-5 pb-2 text-gray-900 placeholder-gray-900  sm:text-sm</value>
      <webElementGuid>0d5e9d39-c40b-4556-a0c7-e26f97ffe607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter destination or hotel name</value>
      <webElementGuid>ea060f72-ef52-4c78-93be-8d19fa4b0332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a6e69c2d-7040-4286-b65b-978ff96b597d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-8</value>
      <webElementGuid>eaf77f47-e8d7-4da8-a18a-3c190d7322f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>fad83824-737f-48a2-bad0-ce54c1b7138e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8aede50a-7562-44f5-8ee0-639c3f57247b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-8&quot;)</value>
      <webElementGuid>7bca328f-3554-46c0-b87f-a8b8e47fc31f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-8']</value>
      <webElementGuid>35be32ad-714f-478f-b36e-152eac6b2824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/main/div[2]/div/div[2]/div[2]/div/div/form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>2c9f3516-77e8-442e-b645-1e50a0736d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>c76ed70e-a872-4ffd-99e6-77a522d97eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter destination or hotel name' and @id = 'headlessui-combobox-input-8']</value>
      <webElementGuid>2892ea5c-60dd-4489-98f7-6664f274c54c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
