<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Privacy Policy_email</name>
   <tag></tag>
   <elementGuidId>2eab569e-6d7c-4564-bb4a-6054a12c3941</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>558ca170-2d1b-4be2-a992-a1416522efdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd669e44-b590-49c6-8ed4-7e8f287edd68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fe48d293-ae2f-4b18-a00b-2317a0738bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>65acb404-e319-44de-86e7-78b5dc2ee421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full</value>
      <webElementGuid>dba0f69d-df85-4dea-bcb3-7fad0edcd70f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>E.g. johndoe@email.com</value>
      <webElementGuid>3fd1351d-40e1-4210-afbd-15e92d3a026c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>b9a9e3a7-4636-4bcd-99ea-9a55d6159ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bg_variant</name>
      <type>Main</type>
      <value>gray</value>
      <webElementGuid>1699f99f-d2ed-41b9-bfb2-59bdc2ec5489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-14&quot;)/div[@class=&quot;text-center flex flex-col items-center justify-center px-4&quot;]/div[@class=&quot;inline-block rounded-md max-w-full overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl w-auto h-auto my-8 opacity-100 scale-100&quot;]/div[@class=&quot;max-w-5xl overflow-y-auto p-6&quot;]/div[@class=&quot;w-full md:w-[400px] relative h-auto&quot;]/div[@class=&quot;w-full relative&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full flex flex-col gap-4&quot;]/form[@class=&quot;flex justify-center w-full&quot;]/div[@class=&quot;w-full border-2 p-8 relative flex flex-col rounded-xl gap-4&quot;]/div[@class=&quot;flex flex-col items-center&quot;]/div[@class=&quot;relative border border-gray-300 rounded-md shadow-sm hover:border-gray-700 bg-white px-3 py-2 focus-within:ring-1 focus-within:ring-primary-100 focus-within:border-primary-100 w-full&quot;]/input[@class=&quot;text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full&quot;]</value>
      <webElementGuid>c406f9ca-11f6-4983-bdfc-a59f60b49258</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>b3322964-d19c-41bb-baf3-b7a2255081b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-14']/div/div[2]/div[2]/div/div/div/div[2]/form/div/div/div/input</value>
      <webElementGuid>34c444c0-3cc1-4761-8950-d4674a181f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>338496e1-38ed-473d-8926-8499bc489f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'E.g. johndoe@email.com' and @name = 'email']</value>
      <webElementGuid>8ef32efb-ec82-4597-afd9-ba25accda715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
