<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHOOSE ROOM</name>
   <tag></tag>
   <elementGuidId>b8fac06c-3463-4e87-b683-2e584189c926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d8dd245-5925-4452-80bb-6679a56aa20a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d490a784-8ce9-4c6b-8dda-2aad419f5533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-white bg-blue-500 hover:bg-indigo-700 focus:ring-indigo-500 border border-transparent shadow-sm focus:outline-none  w-full py-2 px-2</value>
      <webElementGuid>dffc94ae-0002-440e-8d35-91d8f7a35b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHOOSE ROOM</value>
      <webElementGuid>91eab812-6d91-43b7-8c33-85197ff6bd39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hotel&quot;)/div[@class=&quot;mt-0 md:mt-18 p-5&quot;]/div[@class=&quot;flex flex-col gap-4 pb-5 mt-4&quot;]/div[@class=&quot;grid grid-cols-2 gap-6&quot;]/div[@class=&quot;col-span-2&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-full h-full border-2 hover:border-2 hover:border-blue-500&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;relative w-full h-full flex flex-col  grow md:flex-row&quot;]/div[@class=&quot;grid grid-cols-12 w-full&quot;]/div[@class=&quot;col-span-12 h-full p-3 gap-2 border-t-2 flex flex-row lg:col-span-4 lg:col-span-4 3xl:col-span-4 lg:border-l-2 lg:flex-col justify-end lg:justify-between lg:border-l-2 md:border-t-0&quot;]/div[@class=&quot;flex justify-between w-full items-center gap-4 lg:items-end lg:flex-col&quot;]/div[@class=&quot;lg:w-full w-40&quot;]/button[@class=&quot;inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-white bg-blue-500 hover:bg-indigo-700 focus:ring-indigo-500 border border-transparent shadow-sm focus:outline-none  w-full py-2 px-2&quot;]</value>
      <webElementGuid>f21e2340-8200-4480-b8a0-c86151415485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[7]</value>
      <webElementGuid>850cf581-3a45-4c59-abd3-4a8914bbf985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='hotel']/div[2]/div[3]/div/div/div/div/div/div[2]/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>6792383f-2457-41a9-a185-21d89db2295e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rooms &amp; Guests'])[1]/following::button[14]</value>
      <webElementGuid>d0b04528-1bb3-4d77-bd50-db83c939ecd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>2800d20b-109e-4e94-9ddb-c8cc1005b863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'CHOOSE ROOM' or . = 'CHOOSE ROOM')]</value>
      <webElementGuid>9734c1a8-ace3-42cd-975f-8185f8cb5a97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
