<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Destination_headlessui-combobox-input-8</name>
   <tag></tag>
   <elementGuidId>2638106e-4983-441e-b32d-f0d81ecbaf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='headlessui-combobox-input-8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-input-8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8dc94ac6-781f-454e-ad8f-d5af995b6c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5afb1663-b9a7-4b40-a940-37a9d7d4c229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>!outline-none border-0 pl-0 outline-transparent  block w-full  truncate pt-5 pb-2 text-gray-900 placeholder-gray-900  sm:text-sm</value>
      <webElementGuid>2d038f83-54c9-48f9-bf19-e7170b4f256d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter destination or hotel name</value>
      <webElementGuid>a517e72c-1503-4205-809a-3b2bb76850dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc6590e6-4dd3-4536-83af-90a4fdb35920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-input-8</value>
      <webElementGuid>398aca20-a6cf-4883-93ed-52f22de19168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>eff01b6e-dfe0-4073-a8c2-3ae38979bbb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60b18830-4d3d-4eae-b52a-6eda4563ac3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>c5bc0664-4e19-46b3-8bfc-d01e27055d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>headlessui-combobox-options-13</value>
      <webElementGuid>a967b707-c585-4707-ae61-1a4c035c4022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-input-8&quot;)</value>
      <webElementGuid>fd920fff-b7e9-4833-8d16-c5498300414f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='headlessui-combobox-input-8']</value>
      <webElementGuid>d3965f4e-28a6-4d5b-9d3a-2e8e3e0759be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/main/div[2]/div/div[2]/div[2]/div/div/form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>8d1ffb11-bc41-47a1-9651-52b9f18962e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>df329724-6d6d-4870-b3f9-2ff703b4de27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Enter destination or hotel name' and @id = 'headlessui-combobox-input-8']</value>
      <webElementGuid>a369b659-1007-4797-86cd-c4858114e0a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
