<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__cursor-pointer</name>
   <tag></tag>
   <elementGuidId>bcdefe32-47ef-4457-bbfa-d658dd5f44f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.cursor-pointer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>939a9bc0-9c3e-47e6-8431-c30d581a51fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/logo.svg 1x, /images/logo.svg 2x</value>
      <webElementGuid>226f4e33-f03b-4a9a-ad96-e5516ed935e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/logo.svg</value>
      <webElementGuid>ca33ce36-a914-432a-a123-57916b91014a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a1dd266d-333d-4d00-956f-943f9ad59d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>intrinsic</value>
      <webElementGuid>6af47d04-9af7-4184-a15a-a25ef6bf2eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer</value>
      <webElementGuid>d2654c7a-3579-4ff9-946c-08f027baed71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;w-full z-50 relative&quot;]/div[@class=&quot;relative bg-white shadow-md w-full z-[50]&quot;]/div[1]/div[@class=&quot;flex items-center justify-between bg-white px-4 py-2&quot;]/span[1]/img[@class=&quot;cursor-pointer&quot;]</value>
      <webElementGuid>d1b7b62e-2057-49f9-ac9f-5a069f34836d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/span/img</value>
      <webElementGuid>13ce9bf2-f2d1-4087-8435-e6bfc324f558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>45417456-ec26-4461-91a6-e9303ada6dfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/logo.svg']</value>
      <webElementGuid>b379024c-4b5f-42fe-86a6-e932edce43c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
