<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ACCEPT</name>
   <tag></tag>
   <elementGuidId>0863a866-f99a-46cf-bb42-bc4a1a7efbbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74d1e1f8-dfba-4620-8ef8-9fb594e7d5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5fe2f44-b834-4007-8d5d-0071e583469d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-gray-600 bg-transparent hover:bg-gray-100 focus:ring-indigo-500 border border-gray-600 focus:outline-none  px-2 py-2 text-xs min-w-[110px] max-w-full border-white hover:bg-blue-400</value>
      <webElementGuid>f5073c9d-fbde-42ba-8c8a-c62859e2ba21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCEPT</value>
      <webElementGuid>fc158e09-bab2-4a48-baf7-e99fc3462eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;w-full z-50 relative&quot;]/div[@class=&quot;fixed z-50  left-10 bottom-10&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto bg-blue-500 m-2 p-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;grid grid-cols-3&quot;]/div[@class=&quot;flex justify-end justify-items-center place-items-center&quot;]/button[@class=&quot;inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-gray-600 bg-transparent hover:bg-gray-100 focus:ring-indigo-500 border border-gray-600 focus:outline-none  px-2 py-2 text-xs min-w-[110px] max-w-full border-white hover:bg-blue-400&quot;]</value>
      <webElementGuid>8b9a7521-ac13-4897-8e75-1397666d1643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>04c0e18b-98e8-4af5-8101-0ea1af6a2079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>f139b2bf-5898-43e8-8d04-4e3ed5fb2555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[1]</value>
      <webElementGuid>ebcd9975-898f-4f36-94b1-100630d3ced7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/preceding::button[1]</value>
      <webElementGuid>8dd5ab22-34a0-4ed0-8e3a-3c8193fea3da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Destination'])[1]/preceding::button[4]</value>
      <webElementGuid>053f05a0-b3a9-4737-b660-ba8120a43140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>26127497-2e9d-456e-b9f0-78aa4d88f702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ACCEPT' or . = 'ACCEPT')]</value>
      <webElementGuid>f2d902cf-d56f-410b-b3cd-8a989c1e83b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
