<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Munich, Germany</name>
   <tag></tag>
   <elementGuidId>c6e53c4e-8583-4382-a963-33ddcea6d6fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='headlessui-combobox-option-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#headlessui-combobox-option-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4ca3c876-fff3-4482-960d-a8b6ca0f596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cursor-pointer select-none relative py-3 pl-4 pr-4 text-white bg-primary-100</value>
      <webElementGuid>0c7fbe6d-8265-4590-bd9f-e9599be9c332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>headlessui-combobox-option-16</value>
      <webElementGuid>db9225f8-cc84-4841-91b2-5330f25155dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>edb08d02-36ae-48ff-9068-e0db6b83a4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>bf6f961f-29e0-4a8d-8811-ae3d0cbde9f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68018ebe-5f8d-4a61-91db-ba1e176f3a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-headlessui-state</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>3f114956-1f11-4712-be8d-f60e7723a9f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Munich, Germany</value>
      <webElementGuid>034b6406-bd7d-48b7-b100-adf9c381331a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-combobox-option-16&quot;)</value>
      <webElementGuid>a74b7ba5-54c1-4267-88ad-a0f2cdc990fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='headlessui-combobox-option-16']</value>
      <webElementGuid>6cec5256-b1da-4f3b-8dbe-6c35d1711e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='headlessui-combobox-options-13']/div/li</value>
      <webElementGuid>4096f1fb-46a5-4d13-9f0a-4c376de5396c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::li[1]</value>
      <webElementGuid>e6fd873d-9e30-422e-a120-d719160e80d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML &amp; KYC Policy'])[1]/following::li[2]</value>
      <webElementGuid>cfaf7932-d469-4541-b9f4-e36487b7c9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'headlessui-combobox-option-16', '&quot;', ')')])[1]/preceding::li[10]</value>
      <webElementGuid>10f9ced5-9f26-47af-9904-59deb9dc6cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>200055dc-69a2-49cc-9fa7-bd0c5e109184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'headlessui-combobox-option-16' and (text() = 'Munich, Germany' or . = 'Munich, Germany')]</value>
      <webElementGuid>4ccdbceb-f4f7-48fb-8a51-13287d5d2c39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
