<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Privacy Policy_password</name>
   <tag></tag>
   <elementGuidId>ea3b0f82-32a2-4fb5-a9cc-d9b835654860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1bbad62a-40a4-4f2c-882c-020e05af1877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>48cb4134-4559-4a32-ae45-ab2ef2fa8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fcd32210-49de-4877-804a-748be9af0c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>0335bb79-3d84-4bb1-9b1f-4686fa04afce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full</value>
      <webElementGuid>4815b588-c179-4bc8-96fa-e1a60f502a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter password</value>
      <webElementGuid>43331e5b-c172-422f-9250-5f6947bf8e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a9f29ddc-380e-462f-ba1d-340c0f2cfda0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bg_variant</name>
      <type>Main</type>
      <value>gray</value>
      <webElementGuid>22e7a8c4-1737-4923-9ce8-cb1a4e684dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-14&quot;)/div[@class=&quot;text-center flex flex-col items-center justify-center px-4&quot;]/div[@class=&quot;inline-block rounded-md max-w-full overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl w-auto h-auto my-8 opacity-100 scale-100&quot;]/div[@class=&quot;max-w-5xl overflow-y-auto p-6&quot;]/div[@class=&quot;w-full md:w-[400px] relative h-auto&quot;]/div[@class=&quot;w-full relative&quot;]/form[@class=&quot;flex justify-center w-full mt-4&quot;]/div[@class=&quot;border-2 p-8 relative rounded-xl flex flex-col gap-4&quot;]/div[@class=&quot;justify-center&quot;]/div[@class=&quot;relative border border-gray-300 rounded-md shadow-sm hover:border-gray-700 bg-white px-3 py-2 focus-within:ring-1 focus-within:ring-primary-100 focus-within:border-primary-100 w-full&quot;]/input[@class=&quot;text-gray-900 placeholder-gray-400 bg-white font-normal sm:text-sm  text-sm focus:outline-none placeholder:font-light w-full py-2 w-full&quot;]</value>
      <webElementGuid>f349fcf7-0fb2-42ff-a5ab-ea835dd2549d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>42b6f116-2375-4125-b3c0-0a6c4d19982b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-14']/div/div[2]/div[2]/div/div/form/div/div/div/input</value>
      <webElementGuid>cd6df3cd-790b-480b-882e-4a785f08aff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/input</value>
      <webElementGuid>1e7e7bee-56f4-455a-a7cf-c152f188f84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Enter password' and @name = 'password']</value>
      <webElementGuid>59b08d70-9b3b-44d3-91ab-388619289258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
