<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ACCEPT</name>
   <tag></tag>
   <elementGuidId>5a15e127-b901-40e5-96a7-70ca476c9aba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>70d419fb-8e03-4eff-899d-f6ac26904da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7d8a23e-8939-42fd-b2b9-a9c2c8eaf3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-gray-600 bg-transparent hover:bg-gray-100 focus:ring-indigo-500 border border-gray-600 focus:outline-none  px-2 py-2 text-xs min-w-[110px] max-w-full border-white hover:bg-blue-400</value>
      <webElementGuid>534a910f-c531-432c-8fee-1c68afbe8954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCEPT</value>
      <webElementGuid>69cf37d9-888c-4a78-a15c-b5687c3446f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[1]/div[@class=&quot;w-full z-50 relative&quot;]/div[@class=&quot;fixed z-50  left-10 bottom-10&quot;]/div[@class=&quot;relative flex flex-col border border-gray-200 shadow-lg rounded-md bg-white w-auto bg-blue-500 m-2 p-2&quot;]/div[@class=&quot;grow w-full&quot;]/div[@class=&quot;grid grid-cols-3&quot;]/div[@class=&quot;flex justify-end justify-items-center place-items-center&quot;]/button[@class=&quot;inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-gray-600 bg-transparent hover:bg-gray-100 focus:ring-indigo-500 border border-gray-600 focus:outline-none  px-2 py-2 text-xs min-w-[110px] max-w-full border-white hover:bg-blue-400&quot;]</value>
      <webElementGuid>d1b4c152-18a2-479e-b528-75c3c838325e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>b5834a0b-af80-4063-a13d-c3096d98521e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div[2]/button</value>
      <webElementGuid>a7f21992-2a0f-4991-a90c-1fed5db589b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn more'])[1]/following::button[1]</value>
      <webElementGuid>179f2ca5-48ba-4d24-9bf0-54232a6fa872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/preceding::button[1]</value>
      <webElementGuid>d66fe9ca-b8c0-4062-ab5c-364b4d25bdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lock'])[1]/preceding::button[2]</value>
      <webElementGuid>5458a282-488d-4697-a193-32b0b8a16c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>7737b934-bbc2-40d6-9c58-73f35e2384d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ACCEPT' or . = 'ACCEPT')]</value>
      <webElementGuid>f3f5f9a6-da1f-4eae-adfb-c2dd9c9125f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
