<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Enter with Facebook</name>
   <tag></tag>
   <elementGuidId>36673084-5b78-4366-8643-00aeeb60eea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4e92b55a-3ab9-41c5-bf96-c7a7f7a0e4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>175dd958-a6ff-4130-ac3f-d2866fdce1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-white bg-blue-500 hover:bg-indigo-700 focus:ring-indigo-500 border border-transparent shadow-sm focus:outline-none  px-4 py-2 text-sm min-w-[150px] max-w-full w-full px-10 bg-blue-800</value>
      <webElementGuid>86ddea21-91a1-435a-b36e-b1d6be12315f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Enter with Facebook</value>
      <webElementGuid>adc0e0d0-3798-4e97-bc4b-78e9ed60adb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headlessui-dialog-14&quot;)/div[@class=&quot;text-center flex flex-col items-center justify-center px-4&quot;]/div[@class=&quot;inline-block rounded-md max-w-full overflow-hidden text-left align-middle transition-all transform bg-white shadow-xl w-auto h-auto my-8 opacity-100 scale-100&quot;]/div[@class=&quot;max-w-5xl overflow-y-auto p-6&quot;]/div[@class=&quot;w-full md:w-[400px] relative h-auto&quot;]/div[@class=&quot;w-full relative&quot;]/div[@class=&quot;w-full&quot;]/div[@class=&quot;w-full flex flex-col gap-4&quot;]/div[2]/button[@class=&quot;inline-flex items-center justify-center relative rounded-md no-underline hover:no-underline rounded-md text-white bg-blue-500 hover:bg-indigo-700 focus:ring-indigo-500 border border-transparent shadow-sm focus:outline-none  px-4 py-2 text-sm min-w-[150px] max-w-full w-full px-10 bg-blue-800&quot;]</value>
      <webElementGuid>b19cb6a1-5c87-42b1-a048-ff914a11c237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>802fdcbc-c940-4bbe-a19d-8232e83508fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='headlessui-dialog-14']/div/div[2]/div[2]/div/div/div/div[2]/div[2]/button</value>
      <webElementGuid>d41222e1-a269-46f7-8c8d-411551d82890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::button[4]</value>
      <webElementGuid>be6bbe91-18b5-4c52-91ab-32cde4ff3e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AML &amp; KYC Policy'])[1]/following::button[4]</value>
      <webElementGuid>b3322f18-2a39-4b5a-b762-f812e2fff571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>02da337c-43af-4522-a395-367f7cdbb1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Enter with Facebook' or . = 'Enter with Facebook')]</value>
      <webElementGuid>9a648c06-60d4-4058-bd20-9c487f899df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
